subtask_series: [enh, asr]

model_conf:
  calc_enh_loss: false
  enh_frontend_no_grad: true
  bypass_enh_prob: 0.0

enh_model_conf:
  loss_type: si_snr

enh_encoder: conv
enh_encoder_conf:
  channel: 256
  kernel_size: 40
  stride: 20
enh_decoder: conv
enh_decoder_conf:
  channel: 256
  kernel_size: 40
  stride: 20
enh_separator: tcn
enh_separator_conf:
  num_spk: 1
  layer: 4
  stack: 2
  bottleneck_dim: 256
  hidden_dim: 512
  kernel: 3
  causal: false
  norm_type: "gLN"
  nonlinear: relu

enh_criterions:
  - name: si_snr
    conf:
      eps: 1.0e-7
    wrapper: fixed_order
    wrapper_conf:
      weight: 1.0

frontend: default
specaug: null
specaug_conf: {}
normalize: utterance_mvn
normalize_conf: {}

asr_preencoder: null
asr_preencoder_conf: {}

asr_encoder: conformer
asr_encoder_conf:
  output_size: 256
  attention_heads: 4
  linear_units: 1024
  num_blocks: 12
  dropout_rate: 0.1
  positional_dropout_rate: 0.1
  attention_dropout_rate: 0.1
  input_layer: conv2d
  normalize_before: true
  macaron_style: true
  rel_pos_type: latest
  pos_enc_layer_type: rel_pos
  selfattention_layer_type: rel_selfattn
  activation_type: swish
  use_cnn_module: true
  cnn_module_kernel: 31

asr_postencoder: null
asr_postencoder_conf: {}

asr_decoder: transformer
asr_decoder_conf:
  attention_heads: 4
  linear_units: 2048
  num_blocks: 6
  dropout_rate: 0.1
  positional_dropout_rate: 0.1
  self_attention_dropout_rate: 0.1
  src_attention_dropout_rate: 0.1

asr_model_conf:
  ctc_weight: 0.3
  lsm_weight: 0.1
  length_normalized_loss: false

optim: adam
init: none
use_amp: true
max_epoch: 200
patience: 20
early_stopping_criterion: [valid, acc, max]
batch_type: numel
batch_bins: 24000000
accum_grad: 16
num_workers: 4
optim_conf:
  lr: 0.0005
  eps: 1.0e-08
  weight_decay: 0.0001

val_scheduler_criterion:
  - valid
  - acc
best_model_criterion:
  - - valid
    - acc
    - max
  - - valid
    - loss
    - min
keep_nbest_models: 10

scheduler: warmuplr
scheduler_conf:
  warmup_steps: 3000

num_att_plot: 0
