# NOTE: DO NOT WRITE DISTRIBUTION-SPECIFIC COMMANDS HERE (e.g., apt, yum, etc.)

# Generated by tools/activate_python.sh
[ -f "$PWD"/tools/activate_python.sh ] && . "$PWD"/tools/activate_python.sh
[ -f "$PWD"/../../tools/activate_python.sh ] && . "$PWD"/../../tools/activate_python.sh
[ -f "$PWD"/../../../tools/activate_python.sh ] && . "$PWD"/../../../tools/activate_python.sh

